- alias: Turn on Vacation/Away Mode
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.current_state
      to: 'on_vacation'
  action:
    # 1 Set away mode in thermostat
    - service: climate.set_preset_mode
      data:
        entity_id: group.climate
        preset_mode: 'away'
    # turn off all lights and recirculation pump
    - service: switch.turn_off
      data:
        entity_id:
          - group.indoor_lights
          - switch.recirc_pump
    # Turn off media players
    - service: media_player.turn_off
      data:
        entity_id: group.monoprice
    # Close main floor shades
    - service: scene.turn_on
      data:
        entity_id:
          - scene.34003 # Dining Closed
          - scene.56015 # Living Closed
    - service: notify.telegram_egor
      data:
        message: Turning Vacation mode on. Have a good vacation!
