- alias: Turn on Vacation/Away Mode
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.current_state
      to: 'on_vacation'
  action:
    # 1 Set away mode in thermostat
    - service: climate.set_away_mode
      data:
        entity_id: group.climate
        away_mode: true
    - service: notify.telegram_egor
      data:
        message: Turning Vacation mode on. Have a good vacation!
    # turn off all lights and recirculation pump
    - service: switch.turn_off
      data:
        entity_id:
          - group.indoor_lights
          - switch.recirc_pump
    # Turn off media players
    - service: media_player.turn_off
      data:
        entity_id: group.monoprice
