# Turn off automatic away mode
- alias: Turn off automatic away mode
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.current_state
      from: 'away'
      to: 'home'
  action:
    # Verify that shades are in proper scenes
    - service: python_script.home_shades
    # Send a notification
    - service: notify.telegram_egor
      data:
        message: Somebody is home. Cancelling Away mode.
    # Cancel away mode on all thermostats
    - service: climate.set_preset_mode
      data:
        entity_id: group.climate
        preset_mode: 'home'
