
# Turn off automatic away mode
- alias: Turn off automatic away mode
  hide_entity: True
  trigger:
    - platform: state
      entity_id: sensor.current_state
      from: 'away'
      to: 'home'
  # Exit from away mode
  action:
    - service: notify.telegram_egor
      data:
        message: Somebody is home. Cancelling Away mode.
    - service: climate.set_away_mode
      data:
        entity_id: group.climate
        away_mode: false
