# Turns off all lights/zones/devices when alarm is set at night
- alias: Turn off all lights when at night
  hide_entity: True
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: 'armed_away'
  condition:
    condition: and
    conditions:
      # We are home
      - condition: state
        entity_id: sensor.current_state
        state: 'home'
      # And it is night time
      - condition: state
        entity_id: binary_sensor.night
        state: 'on'
  # Turn off all lights except master bedroom + ensuite
  action:
    - service: notify.telegram_egor
      data:
        message: Bed time. Turning off all lights
    - service: switch.turn_off
      data:
        entity_id:
          - group.basement_lights
          - group.ground_floor_lights
          - group.loft_lights
          - switch.laundry
          - switch.guest_bedroom
          - switch.craft_room
          - switch.upstairs_hallway
          - group.guest_bathroom_lights
          - switch.deck
    - service: media_player.turn_off
      data:
        entity_id: group.monoprice
