# Runs home_recirc_pump.py every 10 minutes if in home mode
- alias: Run recirc pump automation
  hide_entity: true
  trigger:
    platform: time_pattern
    minutes: '/10'
    seconds: 00
  condition:
    # We are not on vacation
    condition: state
    entity_id: sensor.current_state
    state: 'home'
  action:
    - service: python_script.home_recirc_pump
