# Close shades just after sunset

- alias: Lower shades just after sunset
  hide_entity: True
  trigger:
    platform: template
    value_template: "{% if states.sun.sun.attributes.elevation <=  states.input_number.close_shades_elevation.state|float%}true{%endif%}"
  condition:
    # We are not on vacation
    condition: state
    entity_id: sensor.current_state
    state: 'home'
  # Lower shades everywhere
  action:
    - service: python_script.home_shades

# Open shades in the morning
- alias: Raise shades just after sunrise
  hide_entity: True
  trigger:
    platform: template
    value_template: "{% if states.sun.sun.attributes.elevation >=  states.input_number.open_shades_elevation.state|float%}true{%endif%}"
  condition:
    # We are not on vacation
    condition: state
    entity_id: sensor.current_state
    state: 'home'
  # Raise shades everywhere
  action:
    - service: python_script.home_shades
