# Automatic away mode when nobody is at home during the day
- alias: Turn on automatic away mode
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.somebody_home
      to: 'off'
  condition:
    condition: and
    conditions:
      # We are not on vacation
      - condition: state
        entity_id: input_boolean.on_vacation
        state: 'off'
      # And it is daytime
      - condition: time
        after: '06:00:00'
        before: '20:00:00'
  # Set away mode
  action:
    - service: notify.telegram_egor
      data:
        message: Nobody is at home. Setting away mode.
    - service: switch.turn_off
      data:
        entity_id:
          - group.indoor_lights
    - service: media_player.turn_off
      data:
        entity_id: group.monoprice
    - service: climate.set_away_mode
      data:
        entity_id: group.climate
        away_mode: true

# Turn off automatic away mode
- alias: Turn off automatic away mode
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.somebody_home
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.on_vacation
    state: 'off'
  # Exit from away mode
  action:
    - service: notify.telegram_egor
      data:
        message: Somebody is at home. Cancelling Away mode.
    - service: climate.set_away_mode
      data:
        entity_id: group.climate
        away_mode: false
