# Automatic away mode when nobody is at home during the day,
# and not on vacation
- alias: Turn on automatic away mode
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.somebody_home
      from: 'on'
      to: 'off'
      for:
        minutes: 5
  condition:
    condition: and
    conditions:
      # We are not on vacation
      - condition: state
        entity_id: input_boolean.on_vacation
        state: 'off'
  # Set away mode
  action:
    - service: notify.telegram_egor
      data:
        message: Seems like nobody is at home. Setting away mode.
    # Turn off lights
    - service: switch.turn_off
      data:
        entity_id:
          - group.indoor_lights
    # Turn off media players
    - service: media_player.turn_off
      data:
        entity_id: group.monoprice
    # Set away mode on thermostats
    - service: climate.set_away_mode
      data:
        entity_id: group.climate
        away_mode: true

# Turn off automatic away mode
- alias: Turn off automatic away mode
  hide_entity: True
  trigger:
    - platform: state
      entity_id: binary_sensor.somebody_home
      from: 'off'
      to: 'on'
  condition:
    condition: state
    entity_id: input_boolean.on_vacation
    state: 'off'
  # Exit from away mode
  action:
    - service: notify.telegram_egor
      data:
        message: Somebody is home. Cancelling Away mode.
    - service: climate.set_away_mode
      data:
        entity_id: group.climate
        away_mode: false
