# Sets night input boolean to true after 21:00
- alias: Set night input boolean to true at 21:00
  hide_entity: True
  trigger:
    platform: time
    at: '21:00:00'
  action:
    service: homeassistant.turn_on
    entity_id: input_boolean.night

# Sets night input boolean to false after 21:00
- alias: Set night input boolean to false at 8:00
  hide_entity: True
  trigger:
    platform: time
    at: '8:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: input_boolean.night
