- alias: Turn on Vacation/Away Mode
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_boolean.on_vacation
      to: 'on'
  action:
    # 1 Set away mode in thermostat
    - service: climate.set_away_mode
      data:
        entity_id: group.climate
        away_mode: true
    - service: notify.telegram_egor
      data:
        message: Turning on Vacation mode.
    # TODO add turn off all lights

- alias: Turn off Vacation/AwayMode
  hide_entity: True
  trigger:
    - platform: state
      entity_id: input_boolean.on_vacation
      to: 'off'
  action:
    - service: notify.telegram_egor
      data:
        message: Turning off Vacation mode.
    # Remove away mode from thermostat
    - service: climate.set_away_mode
      data:
        entity_id: group.climate
        away_mode: false
