# Notification if garage door has been open for 5 or more minutes
- alias: Warn if garage door has been open for 5 or more minutes
  hide_entity: True
  trigger:
    - platform: state
      entity_id: cover.garage_door
      to: 'open'
      for:
        minutes: 5
  action:
    - service: notify.telegram_egor
      data:
        message: Warning! Garage door has been open for 5 minutes!
